language: node_js
node_js:
- 14
services:
- postgresql
addons:
  postgresql: '10'
dist: xenial
notifications:
  email:
    on_success: change
    on_failure: always
install:
- npm ci
before_script:
- psql -c 'create database "pits-protectors-graceshopper";' -U postgres
script:
- npm test
- npm run build-client
deploy:
  api_key:
    secure: KJTflgFOr12OHu6M+eqGPeFDTa7mNWFDoLETUazvzTzT5Oduw/CswrHHZLJl5RjbujIRBBtKI9f8LohgZuhtqJYG2bSdAxKVMWp/8eOIyAqyq+QzbgRCUecmeZz9knjRk/XbqtYNYFbwQLLRLpJWFMRKjM3qAP43kWN7bex3rpu+/h+d6NCjHSdjfW7ngWYS/c/qnfIfT/dGD5yJrDEzKfP0hhbwvtDxlgn79aOjQA95BYo2M/kYuYHix2Pz7n2IwhFYJ5wH35T5XAEbiDfwIBFlt9WX3LH0dPVO0ywzXN9T2ETu7psQmFyeO4at1+DBBH+1FBWFF1J7Lx+9p3q6CiSYNqvy6LghLvOo905fR/4OAclTDmwRLGy18uq10e226cSPtIP+rHjlqPcyNk5P+qD2fqlhOgH+C9ga6l6xX4PXVeAPo/if3jwRhQzsQgIN0N41zqBxRgIUOmO3eJGRXc8wQZLVrnR6M9Bje5Ho6c6rqWq837dyengxUoUhho8HOw3Z65Xzm94OnOVlsBR9YYguyZR1FWZYTCVH7yexq6lyDHqGgpAXqqibeuURl/7n5D9HRqWqOw4+4Yzmw0UQRu485YlK4cla24HHwAeQDR7+Lmu/hqzJyIbd1zkE5BvJEgt4nd8OmCBtkaJWWMbNMuNfWw/jhJ4jHwKRE2D7WsI=
